### ISSUE TITLE
How you get Ro?

### ISSUE THREAD

**Issue by fega** [labay11/MQ-2-sensor-library#1]
Hello , I want to know, how you determine Ro in your library? thanks

**Comment by yanoschik** [comment]
Just read the code and you'll find calibration at startup...
(btw. I got this lib slightly updated [MQ2Lib](https://github.com/yanoschik/MQ2Lib))

**Comment by labay11** [comment]
It's done in the `begin()` method in [MQ2.cpp](https://github.com/xerlay11/MQ-2-sensor-library/blob/master/MQ2.cpp) which assigns the value returned by `MQCalibration()`

And thank's to @yanoschik for updating this library.
